version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports: ["27017:27017"]
    volumes: ["mongodb_data:/data/db"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  customer-service:
    build: ./customer-service
    ports: ["3001:3001"]
    environment:
      PORT: 3001
      MONGODB_URI: mongodb://root:example@mongodb:27017/customer_db?authSource=admin
    depends_on: ["mongodb"]

  item-service:
    build: ./item-service
    ports: ["3002:3002"]
    environment:
      PORT: 3002
      MONGODB_URI: mongodb://root:example@mongodb:27017/item_db?authSource=admin
    depends_on: ["mongodb"]

  order-service:
    build: ./order-service
    ports: ["3003:3003"]
    environment:
      PORT: 3003
      MONGODB_URI: mongodb://root:example@mongodb:27017/order_db?authSource=admin
    depends_on: ["mongodb", "customer-service", "item-service"]

  auth-service:
    build: ./auth-service
    ports: ["3004:3004"]
    environment:
      PORT: 3004
      MONGODB_URI: mongodb://root:example@mongodb:27017/auth_db?authSource=admin
      JWT_SECRET: your_jwt_secret_key
    depends_on: ["mongodb"]

  api-gateway:
    build: ./api-gateway
    ports: ["3000:3000"]
    environment:
      PORT: 3000
      JWT_SECRET: your_jwt_secret_key
    depends_on: ["customer-service", "item-service", "order-service", "auth-service"]

volumes:
  mongodb_data: